// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV6dlcAXD8W-iWtrwvOx2dXt37u8cQ48U',
    appId: '1:556905473190:web:b4fad4b652e4b8d1548067',
    messagingSenderId: '556905473190',
    projectId: 'flutter-chat-app-45a0a',
    authDomain: 'flutter-chat-app-45a0a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-45a0a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoarjEC8P7IrEpV-QmTZaFPO-I_wy39LU',
    appId: '1:556905473190:android:661e62e27bd4a93d548067',
    messagingSenderId: '556905473190',
    projectId: 'flutter-chat-app-45a0a',
    storageBucket: 'flutter-chat-app-45a0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwMj3MiuL56BRvzRNX7Xe_v_gnG2vrlg',
    appId: '1:556905473190:ios:eea3c45c0496ce4c548067',
    messagingSenderId: '556905473190',
    projectId: 'flutter-chat-app-45a0a',
    storageBucket: 'flutter-chat-app-45a0a.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWwMj3MiuL56BRvzRNX7Xe_v_gnG2vrlg',
    appId: '1:556905473190:ios:eea3c45c0496ce4c548067',
    messagingSenderId: '556905473190',
    projectId: 'flutter-chat-app-45a0a',
    storageBucket: 'flutter-chat-app-45a0a.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV6dlcAXD8W-iWtrwvOx2dXt37u8cQ48U',
    appId: '1:556905473190:web:22dc9158f59ec458548067',
    messagingSenderId: '556905473190',
    projectId: 'flutter-chat-app-45a0a',
    authDomain: 'flutter-chat-app-45a0a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-45a0a.appspot.com',
  );

}